name: wedding_app
description: "A new Flutter project about wddings and events common."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  dots_indicator: ^4.0.1
  carousel_slider: ^5.0.0
  easy_localization: ^3.0.7
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.3.4
  queen_validators: ^1.0.1
  bcrypt: ^1.1.3
  bot_toast: ^4.1.3
  lottie: ^3.3.1
  webview_flutter: ^4.10.0
  another_stepper: ^1.2.2
  mockito: ^5.4.5
  flutter_dotenv: ^6.0.0
  pretty_dio_logger: ^1.4.0
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.6
  equatable: ^2.0.7
  device_preview: ^1.3.1
  mobile_scanner: ^7.0.1
  animated_bottom_navigation_bar: ^1.4.0
  url_launcher: ^6.3.2
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  intl_phone_field: ^3.2.0
  pinput: ^5.0.2
  go_router: ^16.2.4
  internet_connection_checker: ^3.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^7.0.0
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.17
  build_runner: ^2.4.13
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0-dev.17
  auto_route_generator: ^10.2.4
  flutter_gen_runner: ^5.8.0
  freezed: ^3.2.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.4
dependency_overrides:
  analyzer_plugin: ^0.13.1

flutter_launcher_icons:  # <-- ضع هذا القسم هنا (على نفس مستوى dependencies)
  android: true
  ios: true
  image_path: "assets/images/im_wedding.png" 
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21

  remove_alpha_ios: true 
# ---------------------


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - .env
    
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Medium.ttf
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_gen:
  integrations:
    flutter_svg: true
flutter_intl:
  enabled: true
